# Параметры менеджера контроллеров ROS 2 Control
controller_manager:
  ros__parameters:
    update_rate: 50         
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50.0
# Описание контроллера дифференциального привода
diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.08      # Расстояние между колесами, м
    wheel_radius: 0.0335          # Радиус колес, м 
    base_frame_id: base_link    
    odom_frame_id: odom         
    publish_rate: 50.0         
    cmd_vel_timeout: 0.5        
    # Лимиты :
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.5   # м/с
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 1.0  # рад/с


